#!/bin/bash

# Copyright (c) 2018, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
#
# Copyright (c) 2018, UChicago Argonne LLC,
#   operator of Argonne National Laboratory
#
# LLNL-CODE-745961
# All rights reserved.
#
# This is the license for KVTree.
# For details, see https://github.com/LLNL/KVTree
# Please read the LICENSE file for full license text.

test=`$1 $2/flush.scr`
expected=`cat $2/flush_file_print.scr`

if [[ "$test" != "$expected" ]]; then
    exit 1
fi
exit 0
