name: kvtree build and test

permissions:
  actions: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [Debug, Release]
        mpi: [seq, par]

    name: ${{ matrix.os }}-${{ matrix.target }}-${{ matrix.mpi }}

    runs-on: ${{ matrix.os }}

    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          path: kvtree
          fetch-depth: 0

      - name: get deps
        uses: ecp-veloc/github-actions/get-scr-os-deps@main
        with:
          os: ${{ matrix.os }}
          mpi: ${{ matrix.mpi }}

      - name: build static
        uses: ecp-veloc/github-actions/cmake-build-static@main
        with:
          component: kvtree
          target: ${{ matrix.target }}
          cmake_line: "-DMPI=${{ matrix.mpi == 'par' }}"

      - name: build and test
        uses: ecp-veloc/github-actions/cmake-build-test@main
        with:
          component: kvtree
          target: ${{ matrix.target }}
          cmake_line: "-DMPI=${{ matrix.mpi == 'par' }}"
